language: python
dist: bionic
os: linux

python:
  - "3.6"
  - "3.7"
  - "3.8"

sudo: false

before_install:
  - pip install --upgrade setuptools==49.6.0
  - pip install --upgrade pip==18.1
  - pip install -r "requirements.txt"
  - pip install flake8
  - pip install coveralls
  - gem install github-linguist
  - pip install bandit
  - pip install pylint
  - pip install execnet
  - wget https://github.com/fossology/fossology/releases/download/3.8.1/FOSSology-3.8.0-debian9stretch.tar.gz
  - tar -xzf FOSSology-3.8.0-debian9stretch.tar.gz
  - sudo apt-get update -y
  - sudo apt-get -y install ./packages/fossology-common_3.8.1-1_amd64.deb ./packages/fossology-nomos_3.8.1-1_amd64.deb
  - sudo apt-get install cloc
  - eval "$(gimme stable)"

install:
  - ./setup.py install

before_script:
  - mkdir exec
  - cd exec
  - go get -u github.com/boyter/scc/
  - cd /home/travis/build/chaoss/grimoirelab-graal/exec
  - git clone https://github.com/nexB/scancode-toolkit.git
  - cd scancode-toolkit
  - git checkout -b test_scancli 96069fd84066c97549d54f66bd2fe8c7813c6b52
  - ./scancode --help
  - cd /home/travis/build/chaoss/grimoirelab-graal/exec
  - wget https://github.com/crossminer/crossJadolint/releases/download/Pre-releasev2/jadolint.jar
  - cd /home/travis/build/chaoss/grimoirelab-graal

script:
  - flake8 . --exclude=exec
  - cd tests
  - coverage run --source=graal run_tests.py

after_success:
  - coveralls
